"""initial schema

Revision ID: 1903a33eeb3e
Revises: 
Create Date: 2026-05-27 14:28:41.267234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1903a33eeb3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='tenantstatus'), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_tenants_api_key_hash', 'tenants', ['api_key_hash'], unique=False)
    op.create_index('ix_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('fine_tune_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='finetunestatus'), nullable=False),
    sa.Column('model_type', sa.Enum('EMBEDDING', 'LLM', name='modeltype'), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fine_tune_jobs_status', 'fine_tune_jobs', ['status'], unique=False)
    op.create_index('ix_fine_tune_jobs_tenant_id', 'fine_tune_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fine_tune_jobs_tenant_id', table_name='fine_tune_jobs')
    op.drop_index('ix_fine_tune_jobs_status', table_name='fine_tune_jobs')
    op.drop_table('fine_tune_jobs')
    op.drop_index('ix_tenants_status', table_name='tenants')
    op.drop_index('ix_tenants_api_key_hash', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
