"""add documents table

Revision ID: 8f8b9e0cf6f6
Revises: ec377835161e
Create Date: 2026-05-31 20:17:45.498552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8b9e0cf6f6'
down_revision: Union[str, Sequence[str], None] = 'ec377835161e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'UPDATING', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    op.create_index('ix_documents_tenant_id_source_file', 'documents', ['tenant_id', 'source_file'], unique=False)
    op.create_index('ix_documents_tenant_id_status', 'documents', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tenant_id_status', table_name='documents')
    op.drop_index('ix_documents_tenant_id_source_file', table_name='documents')
    op.drop_index('ix_documents_tenant_id', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
