"""add usage_events table

Revision ID: ec377835161e
Revises: 1903a33eeb3e
Create Date: 2026-05-27 15:22:24.071606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec377835161e'
down_revision: Union[str, Sequence[str], None] = '1903a33eeb3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('QUERY', 'INGEST', name='eventtype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_events_created_at', 'usage_events', ['created_at'], unique=False)
    op.create_index('ix_usage_events_event_type', 'usage_events', ['event_type'], unique=False)
    op.create_index('ix_usage_events_tenant_id', 'usage_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_tenant_id', table_name='usage_events')
    op.drop_index('ix_usage_events_event_type', table_name='usage_events')
    op.drop_index('ix_usage_events_created_at', table_name='usage_events')
    op.drop_table('usage_events')
    # ### end Alembic commands ###
